@startuml
!include ../c4/C4_Context.puml

LAYOUT_WITH_LEGEND()

'skinparam linetype ortho
skinparam ArrowThickness 3
skinparam Nodesep 92
skinparam Ranksep 192

AddRelTag("maintain", $textColor="red", $lineColor="red", $legendText="Maintain")
AddRelTag("use", $textColor="gray", $lineColor="lightgray", $legendText="Use")
AddRelTag("extend", $textColor="purple", $lineColor="purple", $legendText="Extend")
AddRelTag("push", $textColor="blue", $lineColor="blue", $legendText="Push")
AddRelTag("pull", $textColor="green", $lineColor="green", $legendText="Pull")

Enterprise_Boundary(g, "Gradle, the Company") {

    Enterprise_Boundary(g_ge, "Gradle Enterprise Department") {
        Person_Ext(ge_eng, "Gradle Enterprise Team", "")
        System_Ext(ge, "Gradle Enterprise", "The tool of choice for the world’s most valuable global business and technology brands that compete on the delivery speed and quality of their code.")
    }

    Enterprise_Boundary(g_gbt, "Gradle Build Tool Department") {

        Person(gbt_eng, "Gradle Build Tool\nengineers", "Software developers working on the Gradle Build Tool")

        System(gbt, "Gradle Build Tool", "Gradle Build Tool is the fast and dependable open source build system that automates building software of any type, size or complexity.")
        System(profiler, "Gradle Profiler", "A tool for gathering profiling and benchmarking information for Gradle builds.")
        System(portal, "Gradle Plugin Portal", "A repository hosting community Gradle plugins.")
        System(forums, "Gradle Forums")

        System(actions, "Gradle Actions", "")
        System(completion, "Gradle Completion", "")

        System(distributions, "Gradle Build Tool Distributions", "")
    }

}

Enterprise_Boundary(ext, "External") {
    Person_Ext(software_dev, "Software developer", "Android developer, Java backend developer, etc...")
    Person_Ext(build_eng, "Build engineer", "Member of the central build team of their organization, or simply someone responsible for the build in a software development team.")
    Person_Ext(plugin_author, "Community plugin author", "Individual who maintains an integration with a specific tool with Gradle and publishes it to the Plugin Portal.")
    Person_Ext(platform_provider, "Platform provider", "Team responsible for a plugin or a suite of plugins for an entire ecosystem like Android or Kotlin.")

    System_Ext(ide, IDEs, "IntelliJ IDEA, Android Studio, VSCode etc...")
    System_Ext(ci, "Continuous integration systems", "TeamCity, GitHub, Jenkins, Bamboo etc...")
    System_Ext(repos, "Artifact repositories", "Maven Central, Google etc...")
    System_Ext(idp, "Gradle Identity Provider")
}




Rel(gbt_eng, gbt,, $tags="maintain")
Rel(gbt_eng, profiler,, $tags="maintain")
Rel(gbt_eng, portal,, $tags="maintain")
Rel(gbt_eng, actions,, $tags="maintain")
Rel(gbt_eng, completion,, $tags="maintain")
Rel(gbt_eng, distributions,, $tags="maintain")
Rel(gbt_eng, forums,, $tags="maintain")

Rel(ge_eng, ge,, $tags="maintain")

Rel(software_dev, ide,, $tags="use")
Rel(software_dev, gbt,, $tags="use")
Rel(software_dev, portal,, $tags="use")
Rel(software_dev, ge,, $tags="use")

Rel(build_eng, ide,, $tags="use")
Rel(build_eng, gbt,, $tags="extend")
Rel(build_eng, portal,, $tags="use")
Rel(build_eng, ge,, $tags="use")
Rel(build_eng, profiler,, $tags="use")

Rel(plugin_author, gbt,, $tags="extend")
Rel(plugin_author, portal, Publishes plugins, $tags="push")
Rel(plugin_author, repos, Publishes plugins, $tags="push")

Rel(platform_provider, gbt,, $tags="extend")
Rel(platform_provider, portal, Publishes plugins, $tags="push")
Rel(platform_provider, repos, Publishes plugins, $tags="push")

Rel(ide,gbt,, $tags="use")
Rel(gbt,ge, "Build Scans",, $tags="push")
Rel(gbt,ge, "Build Cache",, $tags="push")
Rel(gbt,ge, "Build Cache",, $tags="pull")
Rel(gbt,portal,, $tags="pull")
Rel(portal, idp,, $tags="use")
Rel(forums, idp,, $tags="use")
Rel(repos,gbt,, $tags="pull")
Rel(gbt,repos,, $tags="push")
Rel_L(profiler,gbt, Runs, $tags="use")
Rel(gbt,profiler, Runs, $tags="use")
Rel(ci,gbt, Runs, $tags="use")
Rel(ci,profiler, Runs, $tags="use")

SHOW_LEGEND()

@enduml
