name: Generate Diagrams
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  diagrams:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: sudo apt-get install -y graphviz
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew plantUml
      - uses: actions/upload-artifact@v3
        with:
          name: diagrams
          path: build/plantuml/
